import { Challenge } from "../types/types";

export const challenges: Challenge[] = [
  {
    id: 1,
    link: "",
    difficulty: "hard",
    image: "/src/assets/challenge01.png",
    title: "Coming Soon...",
    color: "bg-black",
    description: "Coming Soon...",
    bgGradient: "from-customColor2 to-customColor1",
    buttonBg: "bg-brown_button",
    imagePage: "/src/assets/challenge-images/1.jpg",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-stone-950",

    imagePage: "/src/assets/challenge-images/2.jpg",
    image: "/src/assets/challenge02.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor_lightblue to-customColor_darckblue",
    buttonBg: "bg-black_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-green-950",
    imagePage: "/src/assets/challenge-images/3.jpg",

    image: "/src/assets/challenge03.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor_lightpurpule to-customColor_darckpurpule",
    buttonBg: "bg-purprle_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-orange-950",
    imagePage: "/src/assets/challenge-images/4.jpg",

    image: "/src/assets/challenge04.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor_lightgreen to-customColor_darckgreen",
    buttonBg: "bg-green_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-blue-950",
    imagePage: "/src/assets/challenge-images/5.jpg",

    image: "/src/assets/challenge 05.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor_lightpurpule to-customColor_darckpurpule",
    buttonBg: "bg-purprle_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-gray-950",
    imagePage: "/src/assets/challenge-images/6.jpg",

    image: "/src/assets/challenge06.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor_lightblue to-customColor_darckblue",
    buttonBg: "bg-black_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-blue-950",
    imagePage: "/src/assets/challenge-images/7.jpg",

    image: "/src/assets/challenge07.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor_lightgreen to-customColor_darckgreen",
    buttonBg: "bg-green_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-yellow-950",
    imagePage: "/src/assets/challenge-images/8.jpg",

    image: "/src/assets/challenge08.png",
    title: "Coming Soon...",
    description: "Coming Soon...",
    bgGradient: "from-customColor2 to-customColor1",
    buttonBg: "bg-brown_button",
  },
  {
    id: 1,
    link: "",
    difficulty: "hard",
    color: "bg-red-950",
    image: "/src/assets/challenge09.png",
    title: "Coming Soon...",
    imagePage: "/src/assets/challenge-images/9.jpg",
    description: "Coming Soon... ",
    bgGradient: "from-customColor_lightblue to-customColor_darckblue",
    buttonBg: "bg-black_button",
  },
];
