import { Challenge } from "../types/types";

export const challenges: Challenge[] = [
  {
    id: "I",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/easy/CrudApi.md",
    difficulty: "easy",
    shadow: "hover:shadow-cyan-950",

    image: "/assets/challenge01.png",
    title: "False Knight",
    color: "bg-black",
    description: "Challenge 1",
    bgGradient: "from-customColor2 to-customColor1",
    buttonBg: "bg-brown_button",
    imagePage: "/assets/challenge-images/1.jpg",
  },
  {
    id: "II",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/easy/fileUploader.md",
    difficulty: "easy",
    color: "bg-stone-950",
    shadow: "hover:shadow-stone-500",
    imagePage: "/assets/challenge-images/2.jpg",
    image: "/assets/challenge02.png",
    title: "Hornet",
    description: "Challenge 2",
    bgGradient: "from-customColor_lightblue to-customColor_darckblue",
    buttonBg: "bg-black_button",
  },
  {
    id: "III",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/medium/xoGame.md",
    difficulty: "medium",
    color: "bg-green-950",
    imagePage: "/assets/challenge-images/3.jpg",
    shadow: "hover:shadow-green-900",

    image: "/assets/challenge03.png",
    title: "Mantis Lords",
    description: "Challenge 3",
    bgGradient: "from-customColor_lightpurpule to-customColor_darckpurpule",
    buttonBg: "bg-purprle_button",
  },
  {
    id: "IV",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/medium/VotingSystem.md",
    difficulty: "medium",
    color: "bg-orange-950",
    imagePage: "/assets/challenge-images/4.jpg",
    shadow: "hover:shadow-stone-700",

    image: "/assets/challenge04.png",
    title: "Watcher Knights",
    description: "Challenge 4",
    bgGradient: "from-customColor_lightgreen to-customColor_darckgreen",
    buttonBg: "bg-green_button",
  },
  {
    id: "V",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/medium/ServerMonitoring.md",
    difficulty: "medium",
    color: "bg-blue-950",
    imagePage: "/assets/challenge-images/5.jpg",
    shadow: "hover:shadow-orange-900",

    image: "/assets/challenge 05.png",
    title: "Broken Vessel",
    description: "Challenge 5",
    bgGradient: "from-customColor_lightpurpule to-customColor_darckpurpule",
    buttonBg: "bg-purprle_button",
  },
  {
    id: "VI",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/medium/OnlineForm.md",
    difficulty: "medium",
    color: "bg-gray-950",
    imagePage: "/assets/challenge-images/6.jpg",
    shadow: "hover:shadow-blue-900",

    image: "/assets/challenge06.png",
    title: "Traitor Lord",
    description: "Challenge 6",
    bgGradient: "from-customColor_lightblue to-customColor_darckblue",
    buttonBg: "bg-black_button",
  },
  {
    id: "VII",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/hard/meeting.md",
    difficulty: "hard",
    color: "bg-blue-950",
    imagePage: "/assets/challenge-images/7.jpg",
    shadow: "hover:shadow-red-900",

    image: "/assets/challenge07.png",
    title: "Nightmare King Grimm",
    description: "Challenge 7",
    bgGradient: "from-customColor_lightgreen to-customColor_darckgreen",
    buttonBg: "bg-green_button",
  },
  {
    id: "VIII",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/hard/LearningPlatform.md",
    difficulty: "hard",
    color: "bg-yellow-950",
    imagePage: "/assets/challenge-images/8.jpg",
    shadow: "hover:shadow-purple-950",

    image: "/assets/challenge08.png",
    title: "The Hollow Knight",
    description: "Challenge 8",
    bgGradient: "from-customColor2 to-customColor1",
    buttonBg: "bg-brown_button",
  },
  {
    id: "IX",
    link: "https://github.com/MicroClub-USTHB/Hollow-Dev/blob/main/hard/ChatApp.md",
    shadow: "hover:shadow-yellow-900",
    difficulty: "hard",
    color: "bg-red-950",
    image: "/assets/challenge09.png",
    title: "The Radiance",
    imagePage: "/assets/challenge-images/9.jpg",
    description: "Challenge 9",
    bgGradient: "from-customColor_lightblue to-customColor_darckblue",
    buttonBg: "bg-black_button",
  },
];
